trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build project
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default  # 用你的 Windows 电脑

    steps:
    # 安装 Node.js（必须）
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
        checkLatest: true
      displayName: 'Install Node.js'

    # 安装依赖
    - script: npm install
      displayName: 'npm install'

    # 编译项目（生成 dist）
    - script: npm run build
      displayName: 'npm run build'
